# Installs dependencies, runs tests with pytest, and reports code coverage.

name: Beardless Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      shell: bash
      env:
        BRAWLKEY: ${{ secrets.BRAWLHALLAKEY }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r resources/requirements.txt
        echo "$BRAWLKEY" > "resources/brawlhallaKey.txt"
    - name: Test with pytest
      run: |
        coverage run -m pytest -Wignore
    - name: View code coverage
      run: |
        coverage report -m